import type { Config } from 'tailwindcss'

export default <Config>{
  content: [
    './components/**/*.{js,vue,ts}',
    './layouts/**/*.vue',
    './pages/**/*.vue',
    './plugins/**/*.{js,ts}',
    './nuxt.config.{js,ts}',
    './app.vue'
  ],
  theme: {
    extend: {
      colors: {
        brand: {
          "base": {
            "50": "var(--yc-brand-base-50)",
            "100": "var(--yc-brand-base-100)",
            "200": "var(--yc-brand-base-200)",
            "300": "var(--yc-brand-base-300)",
            "400": "var(--yc-brand-base-400)",
            "500": "var(--yc-brand-base-500)",
            "600": "var(--yc-brand-base-600)",
            "700": "var(--yc-brand-base-700)",
            "800": "var(--yc-brand-base-800)",
            "900": "var(--yc-brand-base-900)",
            "950": "var(--yc-brand-base-950)",
            "DEFAULT": "var(--yc-brand-base-500)",
          },
          "glow": {
            "50": "var(--yc-brand-glow-50)",
            "100": "var(--yc-brand-glow-100)",
            "200": "var(--yc-brand-glow-200)",
            "300": "var(--yc-brand-glow-300)",
            "400": "var(--yc-brand-glow-400)",
            "500": "var(--yc-brand-glow-500)",
            "600": "var(--yc-brand-glow-600)",
            "700": "var(--yc-brand-glow-700)",
            "800": "var(--yc-brand-glow-800)",
            "900": "var(--yc-brand-glow-900)",
            "950": "var(--yc-brand-glow-950)",
            "DEFAULT": "var(--yc-brand-glow-500)",
          },
          "metal": {
            "50": "var(--yc-brand-metal-50)",
            "100": "var(--yc-brand-metal-100)",
            "200": "var(--yc-brand-metal-200)",
            "300": "var(--yc-brand-metal-300)",
            "400": "var(--yc-brand-metal-400)",
            "500": "var(--yc-brand-metal-500)",
            "600": "var(--yc-brand-metal-600)",
            "700": "var(--yc-brand-metal-700)",
            "800": "var(--yc-brand-metal-800)",
            "900": "var(--yc-brand-metal-900)",
            "950": "var(--yc-brand-metal-950)",
            "DEFAULT": "var(--yc-brand-metal-500)",
          },
        },
        neutral: {
          "gray": {
            "0": "var(--yc-neutral-gray-0)",
            "50": "var(--yc-neutral-gray-50)",
            "100": "var(--yc-neutral-gray-100)",
            "200": "var(--yc-neutral-gray-200)",
            "300": "var(--yc-neutral-gray-300)",
            "400": "var(--yc-neutral-gray-400)",
            "500": "var(--yc-neutral-gray-500)",
            "600": "var(--yc-neutral-gray-600)",
            "700": "var(--yc-neutral-gray-700)",
            "800": "var(--yc-neutral-gray-800)",
            "900": "var(--yc-neutral-gray-900)",
            "950": "var(--yc-neutral-gray-950)",
            "DEFAULT": "var(--yc-neutral-gray-500)",
          },
          "tinted": {
            "0": "var(--yc-neutral-tinted-0)",
            "50": "var(--yc-neutral-tinted-50)",
            "100": "var(--yc-neutral-tinted-100)",
            "200": "var(--yc-neutral-tinted-200)",
            "300": "var(--yc-neutral-tinted-300)",
            "400": "var(--yc-neutral-tinted-400)",
            "500": "var(--yc-neutral-tinted-500)",
            "600": "var(--yc-neutral-tinted-600)",
            "700": "var(--yc-neutral-tinted-700)",
            "800": "var(--yc-neutral-tinted-800)",
            "900": "var(--yc-neutral-tinted-900)",
            "950": "var(--yc-neutral-tinted-950)",
            "DEFAULT": "var(--yc-neutral-tinted-500)",
          },
        },
        semantic: {
          "success": {
            "50": "var(--yc-semantic-success-50)",
            "100": "var(--yc-semantic-success-100)",
            "200": "var(--yc-semantic-success-200)",
            "300": "var(--yc-semantic-success-300)",
            "400": "var(--yc-semantic-success-400)",
            "500": "var(--yc-semantic-success-500)",
            "600": "var(--yc-semantic-success-600)",
            "700": "var(--yc-semantic-success-700)",
            "800": "var(--yc-semantic-success-800)",
            "900": "var(--yc-semantic-success-900)",
            "950": "var(--yc-semantic-success-950)",
            "DEFAULT": "var(--yc-semantic-success-500)",
          },
          "warning": {
            "50": "var(--yc-semantic-warning-50)",
            "100": "var(--yc-semantic-warning-100)",
            "200": "var(--yc-semantic-warning-200)",
            "300": "var(--yc-semantic-warning-300)",
            "400": "var(--yc-semantic-warning-400)",
            "500": "var(--yc-semantic-warning-500)",
            "600": "var(--yc-semantic-warning-600)",
            "700": "var(--yc-semantic-warning-700)",
            "800": "var(--yc-semantic-warning-800)",
            "900": "var(--yc-semantic-warning-900)",
            "950": "var(--yc-semantic-warning-950)",
            "DEFAULT": "var(--yc-semantic-warning-500)",
          },
          "error": {
            "50": "var(--yc-semantic-error-50)",
            "100": "var(--yc-semantic-error-100)",
            "200": "var(--yc-semantic-error-200)",
            "300": "var(--yc-semantic-error-300)",
            "400": "var(--yc-semantic-error-400)",
            "500": "var(--yc-semantic-error-500)",
            "600": "var(--yc-semantic-error-600)",
            "700": "var(--yc-semantic-error-700)",
            "800": "var(--yc-semantic-error-800)",
            "900": "var(--yc-semantic-error-900)",
            "950": "var(--yc-semantic-error-950)",
            "DEFAULT": "var(--yc-semantic-error-500)",
          },
          "info": {
            "50": "var(--yc-semantic-info-50)",
            "100": "var(--yc-semantic-info-100)",
            "200": "var(--yc-semantic-info-200)",
            "300": "var(--yc-semantic-info-300)",
            "400": "var(--yc-semantic-info-400)",
            "500": "var(--yc-semantic-info-500)",
            "600": "var(--yc-semantic-info-600)",
            "700": "var(--yc-semantic-info-700)",
            "800": "var(--yc-semantic-info-800)",
            "900": "var(--yc-semantic-info-900)",
            "950": "var(--yc-semantic-info-950)",
            "DEFAULT": "var(--yc-semantic-info-500)",
          },
          "attention": {
            "50": "var(--yc-semantic-attention-50)",
            "100": "var(--yc-semantic-attention-100)",
            "200": "var(--yc-semantic-attention-200)",
            "300": "var(--yc-semantic-attention-300)",
            "400": "var(--yc-semantic-attention-400)",
            "500": "var(--yc-semantic-attention-500)",
            "600": "var(--yc-semantic-attention-600)",
            "700": "var(--yc-semantic-attention-700)",
            "800": "var(--yc-semantic-attention-800)",
            "900": "var(--yc-semantic-attention-900)",
            "950": "var(--yc-semantic-attention-950)",
            "DEFAULT": "var(--yc-semantic-attention-500)",
          },
        },
        // セマンティックロール用の色
        "semantic-success-bg": "var(--yc-semantic-success-bg)",
        "semantic-success-fg": "var(--yc-semantic-success-fg_on_bg)",
        "semantic-success-hover": "var(--yc-semantic-success-hover)",
        "semantic-success-pressed": "var(--yc-semantic-success-pressed)",
        "semantic-success-focus": "var(--yc-semantic-success-focus)",
        "semantic-success-strong": "var(--yc-semantic-success-strong)",
        "semantic-success-subtle": "var(--yc-semantic-success-subtle)",
        "semantic-warning-bg": "var(--yc-semantic-warning-bg)",
        "semantic-warning-fg": "var(--yc-semantic-warning-fg_on_bg)",
        "semantic-warning-hover": "var(--yc-semantic-warning-hover)",
        "semantic-warning-pressed": "var(--yc-semantic-warning-pressed)",
        "semantic-warning-focus": "var(--yc-semantic-warning-focus)",
        "semantic-warning-strong": "var(--yc-semantic-warning-strong)",
        "semantic-warning-subtle": "var(--yc-semantic-warning-subtle)",
        "semantic-error-bg": "var(--yc-semantic-error-bg)",
        "semantic-error-fg": "var(--yc-semantic-error-fg_on_bg)",
        "semantic-error-hover": "var(--yc-semantic-error-hover)",
        "semantic-error-pressed": "var(--yc-semantic-error-pressed)",
        "semantic-error-focus": "var(--yc-semantic-error-focus)",
        "semantic-error-strong": "var(--yc-semantic-error-strong)",
        "semantic-error-subtle": "var(--yc-semantic-error-subtle)",
        "semantic-info-bg": "var(--yc-semantic-info-bg)",
        "semantic-info-fg": "var(--yc-semantic-info-fg_on_bg)",
        "semantic-info-hover": "var(--yc-semantic-info-hover)",
        "semantic-info-pressed": "var(--yc-semantic-info-pressed)",
        "semantic-info-focus": "var(--yc-semantic-info-focus)",
        "semantic-info-strong": "var(--yc-semantic-info-strong)",
        "semantic-info-subtle": "var(--yc-semantic-info-subtle)",
        "semantic-attention-bg": "var(--yc-semantic-attention-bg)",
        "semantic-attention-fg": "var(--yc-semantic-attention-fg_on_bg)",
        "semantic-attention-hover": "var(--yc-semantic-attention-hover)",
        "semantic-attention-pressed": "var(--yc-semantic-attention-pressed)",
        "semantic-attention-focus": "var(--yc-semantic-attention-focus)",
        "semantic-attention-strong": "var(--yc-semantic-attention-strong)",
        "semantic-attention-subtle": "var(--yc-semantic-attention-subtle)",
        // 既存のblueカラーも保持
        blue: {
          50: '#eff6ff',
          100: '#dbeafe',
          200: '#bfdbfe',
          300: '#93c5fd',
          400: '#60a5fa',
          500: '#3b82f6',
          600: '#2563eb',
          700: '#1d4ed8',
          800: '#1e40af',
          900: '#1e3a8a'
        }
      },
      fontFamily: {
        sans: ['Hiragino Kaku Gothic ProN', 'Hiragino Sans', 'Meiryo', 'sans-serif']
      },
      spacing: {
        '18': '4.5rem',
        '22': '5.5rem'
      },
      transitionDuration: {
        '1500': '1500ms',
        '2000': '2000ms'
      }
    }
  }
}